[ req ]
default_bits       = 4096
distinguished_name = req_distinguished_name
req_extensions     = req_ext
x509_extensions    = v3_ca
prompt             = no

[ req_distinguished_name ]
C = VN
ST = HocMon
L = HCM
O = Hashicorp
CN = vault.nthedao.info

[ req_ext ]
subjectAltName = @alt_names

[ v3_ca ]
subjectAltName = @alt_names
basicConstraints = critical, CA:TRUE

[ alt_names ]
IP.1 = 127.0.0.1
IP.2 = 0.0.0.0
IP.3 = 192.168.56.31
DNS.1 = vault.nthedao.info
