# ── cloudflared connector — activates the Cloudflare Tunnel from INSIDE the cluster ────────────
# Deploys the cloudflared connector (HA) that dials OUT to Cloudflare with the tunnel run token, so
# *.fitmate.me traffic flows down the tunnel to in-cluster services. No inbound ports. The token is
# created by the cloud/cloudflare-tunnel module; this module receives it as var.tunnel_token.
# Provider (kubernetes) is generated by the CALLER (root.hcl). See [[production-cloudflare-tunnel]] Phase 3.

locals {
  labels = {
    "app.kubernetes.io/name"       = "cloudflared"
    "app.kubernetes.io/part-of"    = "cloudflare-tunnel"
    "app.kubernetes.io/managed-by" = "terraform"
    "fitmate.io/tunnel"            = var.tunnel_name
  }
}

resource "kubernetes_namespace_v1" "main" {
  metadata {
    name   = var.namespace
    labels = local.labels
  }
}

# The run token, delivered straight from Terraform (cloudflare-tunnel output). cloudflared reads it
# from the TUNNEL_TOKEN env var. (To keep the token out of TF state, swap this for an ESO
# ExternalSecret that syncs fitmate/prod/cloudflared/* from Vault — see the unit's notes.)
resource "kubernetes_secret_v1" "token" {
  metadata {
    name      = "cloudflared-token"
    namespace = kubernetes_namespace_v1.main.metadata[0].name
    labels    = local.labels
  }
  type = "Opaque"
  data = { token = var.tunnel_token }
}

resource "kubernetes_deployment_v1" "main" {
  metadata {
    name      = "cloudflared"
    namespace = kubernetes_namespace_v1.main.metadata[0].name
    labels    = local.labels
  }

  spec {
    replicas = var.replicas

    selector {
      match_labels = { "app.kubernetes.io/name" = "cloudflared" }
    }

    strategy {
      type = "RollingUpdate"
      rolling_update {
        max_unavailable = "0"
        max_surge       = "1"
      }
    }

    template {
      metadata {
        labels = local.labels
        # Roll the pods when the token changes so a rotated tunnel reconnects.
        annotations = { "fitmate.io/token-sha" = sha256(var.tunnel_token) }
      }

      spec {
        # Spread replicas across nodes so one node loss doesn't drop the tunnel. Control-plane nodes
        # are tainted NoSchedule, so cloudflared lands on the agents automatically (no toleration).
        topology_spread_constraint {
          max_skew           = 1
          topology_key       = "kubernetes.io/hostname"
          when_unsatisfiable = "ScheduleAnyway"
          label_selector {
            match_labels = { "app.kubernetes.io/name" = "cloudflared" }
          }
        }

        container {
          name  = "cloudflared"
          image = "${var.image}:${var.image_tag}"
          # Token-based, remotely-managed tunnel: ingress config lives in Cloudflare (Phase 2), so
          # `run` needs only the token (read from TUNNEL_TOKEN). --metrics exposes /ready for probes.
          args = ["tunnel", "--no-autoupdate", "--metrics", "0.0.0.0:2000", "run"]

          env {
            name = "TUNNEL_TOKEN"
            value_from {
              secret_key_ref {
                name = kubernetes_secret_v1.token.metadata[0].name
                key  = "token"
              }
            }
          }

          liveness_probe {
            http_get {
              path = "/ready"
              port = 2000
            }
            initial_delay_seconds = 10
            period_seconds        = 10
            failure_threshold     = 3
          }

          readiness_probe {
            http_get {
              path = "/ready"
              port = 2000
            }
            initial_delay_seconds = 5
            period_seconds        = 10
          }

          resources {
            requests = {
              cpu    = var.resources.requests.cpu
              memory = var.resources.requests.memory
            }
            limits = {
              cpu    = var.resources.limits.cpu
              memory = var.resources.limits.memory
            }
          }

          security_context {
            run_as_non_root            = true
            allow_privilege_escalation = false
            read_only_root_filesystem  = true
            capabilities { drop = ["ALL"] }
          }
        }
      }
    }
  }
}
