terraform {
  required_providers {
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.4.1"
    }
  }
}

# NOTE: no module-local `provider "kubectl"` block on purpose. A module that declares its
# own provider config is a "legacy module" and cannot use count/for_each/depends_on on its
# module call — but we need depends_on so routes apply AFTER the Gateway API CRDs + Gateway
# + backend Services exist. So this module inherits the kubectl provider from the root
# (generated by the terragrunt root.hcl), exactly like shared/helm. The host/token/cert
# vars below are kept for interface compatibility but are consumed by the root provider.
